@startuml
skinparam style strictuml

actor "지역상품권 관리자" as Admin
participant ":플랫폼" as Platform

Admin -> Platform: 1. 가맹점 현황 및 분포 확인 요청
activate Platform

alt 2a. 가맹점 리스트 제공 불가인 경우
    Platform -->> Admin: 2a.1 가맹점 리스트 제공 불가 알림


else 
    Platform -->> Admin: 2. 가맹점 리스트 제공

    Admin -> Platform: 3. 가맹점 선택 후 현황 및 분포 확인 요청

    alt 4a. 현황 및 분포 제공 오류
        Platform -->> Admin: 4a.1 현황 및 분포 제공 오류 알림
    else 
        Platform -->> Admin: 4. 선택된 가맹점의 현황 및 분포 제공
        deactivate Platform
    end
    
end


@enduml