@startuml
skinparam style strictuml

actor ":사용자" as 사용자
participant ":플랫폼" as 플랫폼
participant ":상품권지갑" as 상품권지갑
participant ":금융 시스템" as 금융시스템


사용자 -> 플랫폼 : 결제 요청(결제 금액, 결제 수단)
activate 플랫폼
alt 등록된 결제 수단이 없는 경우
    플랫폼 -->> 사용자 : 결제 수단 누락 메시지 반환
else
    
    플랫폼 -> 금융시스템 : 결제 요청(결제 금액, 결제 수단)
    deactivate 플랫폼
    activate 금융시스템

    금융시스템 -->> 플랫폼 : 요청 결과 반환
    activate 플랫폼

    deactivate 금융시스템

    alt 금융 시스템에서 해당 금액이 결제 불가능한 경우
        플랫폼 -->> 사용자 : 잔액 부족 메시지 반환
    else
        플랫폼 -> 상품권지갑 : 결제금 충전
        deactivate 플랫폼
        activate 상품권지갑
        상품권지갑 -->> 플랫폼 : 결제금 정상 처리 여부 반환
        deactivate 상품권지갑
        activate 플랫폼
        플랫폼 -->> 사용자 : 정상 처리 메시지 반환
        deactivate 플랫폼
    end
end

@enduml