@startuml
skinparam style strictuml

actor ":가맹점주" as Owner
participant ":플랫폼" as System

Owner -> System : 고객 연령대 정보 요청
activate System

loop 최대 5회 반복
    System -> System : 고객 연령대 정보 수집

    break 연령대 정보가 유효한 경우
        System --> Owner : 고객 연령대 정보 전송
    end
end

opt 5회 모두 연령대 정보가 유효하지 않은 경우
    System -->> Owner : 에러 페이지 전송
    deactivate System
end

@enduml